output$group1name<-renderText({
  input$group1
})
output$group1filesinfo<-renderTable({
  input$group1files$name
})
output$group2name<-renderText({
  input$group2
})
output$group2filesinfo<-renderTable({
  input$group2files[1]
})
output$group3name<-renderText({
  input$group3
})
output$group3filesinfo<-renderTable({
  input$group3files[1]
})
output$group4name<-renderText({
  input$group4
})
output$group4filesinfo<-renderTable({
  input$group4files[1]
})
output$group5name<-renderText({
  input$group5
})
output$group5filesinfo<-renderTable({
  input$group5files[1]
})
output$group6name<-renderText({
  input$group6
})
output$group6filesinfo<-renderTable({
  input$group6files[1]
})
